/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import model.bean.Cliente;
import model.dao.ClienteDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.*;
import connection.ConnectionFactory;
import javax.swing.JOptionPane;
/**
 *
 * @author Brunobhs18
 */
public class ClienteView extends javax.swing.JFrame {

    /**
     * Creates new form ClienteView
     */
    public ClienteView() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();
        tblCliente.setRowSorter(new TableRowSorter(modelo));
        
        readClienteView();
    }
    
        public void readClienteView(){
        DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();
        modelo.setNumRows(0);
        ClienteDAO cdao = new ClienteDAO();
        
        for(Cliente c: cdao.read()) {
            modelo.addRow(new Object[]{
            c.getNomecli(),
            c.getEnderecocli(),
            c.getContatocli()
        });
        }
        
    } 
    
    public void readClienteViewForBusca(String bus){
        DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();
        modelo.setNumRows(0);
        ClienteDAO cdao = new ClienteDAO();
        
        for(Cliente c: cdao.readBusca(bus)) {
            modelo.addRow(new Object[]{
            c.getNomecli(),
            c.getEnderecocli(),
            c.getContatocli()
        });
        }
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomecli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEnderecocli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtContatocli = new javax.swing.JTextField();
        btnAddcli = new javax.swing.JButton();
        btnExcluircli = new javax.swing.JButton();
        btnAlterarcli = new javax.swing.JButton();
        btnBuscacli = new javax.swing.JButton();
        txtBuscacli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon.png")).getImage());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("CLIENTE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        txtNomecli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomecliActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Endereço:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Contato:");

        btnAddcli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddcli.setText("Adicionar");
        btnAddcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddcliActionPerformed(evt);
            }
        });

        btnExcluircli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluircli.setText("Excluir");
        btnExcluircli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluircliActionPerformed(evt);
            }
        });

        btnAlterarcli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAlterarcli.setText("Alterar");
        btnAlterarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarcliActionPerformed(evt);
            }
        });

        btnBuscacli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscacli.setText("Buscar");
        btnBuscacli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscacliActionPerformed(evt);
            }
        });

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Endereço", "Contato"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        tblCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblClienteKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nome Cliente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEnderecocli, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomecli, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContatocli, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(380, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddcli)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluircli)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarcli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscacli, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscacli)
                        .addGap(35, 35, 35))))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomecli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEnderecocli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtContatocli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddcli)
                    .addComponent(btnExcluircli)
                    .addComponent(btnAlterarcli)
                    .addComponent(btnBuscacli)
                    .addComponent(txtBuscacli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomecliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomecliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomecliActionPerformed

    private void btnAddcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddcliActionPerformed
        // TODO add your handling code here:
        Cliente c = new Cliente();
        ClienteDAO dao = new ClienteDAO();
        c.setNomecli(txtNomecli.getText());
        c.setEnderecocli(txtEnderecocli.getText());
        c.setContatocli(txtContatocli.getText());
        dao.create(c);

            txtNomecli.setText("");
            txtEnderecocli.setText("");
            txtContatocli.setText("");

        readClienteView();
        
    }//GEN-LAST:event_btnAddcliActionPerformed

    private void btnExcluircliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluircliActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblCliente.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Favor selecionar uma linha valida!");
        } else {
            DefaultTableModel tabelaCliente = (DefaultTableModel) tblCliente.getModel();
            int i = JOptionPane.showConfirmDialog(this, "Deseja excluir essa linha?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if(i == 0){
                Cliente c = new Cliente();
                ClienteDAO dao = new ClienteDAO();
                c.setNomecli(txtNomecli.getText());
                dao.delete(c);

                txtNomecli.setText("");
                txtEnderecocli.setText("");
                txtContatocli.setText("");

                readClienteView();

                JOptionPane.showMessageDialog(this, "Excluido com sucesso!");
            }
        }
        
    }//GEN-LAST:event_btnExcluircliActionPerformed

    private void btnAlterarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarcliActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblCliente.getSelectedRow();
        if (linhaSelecionada != -1){
            Cliente c = new Cliente();
            ClienteDAO dao = new ClienteDAO();
            c.setNomecli(txtNomecli.getText());
            c.setEnderecocli(txtEnderecocli.getText());
            c.setContatocli(txtContatocli.getText());
            dao.update(c);

            txtNomecli.setText("");
            txtEnderecocli.setText("");
            txtContatocli.setText("");

            readClienteView();

        }
    }//GEN-LAST:event_btnAlterarcliActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = tblCliente.getSelectedRow();
        if (linhaSelecionada != -1){
            txtNomecli.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 0).toString());
            txtEnderecocli.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 1).toString());
            txtContatocli.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 2).toString());

        }
    }//GEN-LAST:event_tblClienteMouseClicked

    private void btnBuscacliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscacliActionPerformed
        // TODO add your handling code here:
        readClienteViewForBusca(txtBuscacli.getText());
    }//GEN-LAST:event_btnBuscacliActionPerformed

    private void tblClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblClienteKeyReleased
        // TODO add your handling code here:
        int linhaSelecionada = tblCliente.getSelectedRow();
        if (linhaSelecionada != -1){
            txtNomecli.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 0).toString());
            txtEnderecocli.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 1).toString());
            txtContatocli.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 2).toString());

        }
    }//GEN-LAST:event_tblClienteKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddcli;
    private javax.swing.JButton btnAlterarcli;
    private javax.swing.JButton btnBuscacli;
    private javax.swing.JButton btnExcluircli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtBuscacli;
    private javax.swing.JTextField txtContatocli;
    private javax.swing.JTextField txtEnderecocli;
    private javax.swing.JTextField txtNomecli;
    // End of variables declaration//GEN-END:variables
}
