/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.*;
import connection.ConnectionFactory;
import java.util.Vector;
import model.bean.Fornecedor;
import model.bean.Produto;
import model.dao.ProdutoDAO;
import model.dao.FornecedorDAO;


/**
 *
 * @author Brunobhs18
 */
public class ProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form Produto
     */
    public ProdutoView() {
        initComponents();        
        DefaultTableModel modelo = (DefaultTableModel) tblProduto.getModel();
        tblProduto.setRowSorter(new TableRowSorter(modelo));
        restaurarCombobox();
        
        readProdutoView();
    }

    public void readProdutoView(){
        DefaultTableModel modelo = (DefaultTableModel) tblProduto.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();
        
        for(Produto p: pdao.read()) {
            modelo.addRow(new Object[]{
            p.getCod(),
            p.getNomeprod(),
            p.getFornecedorp(),
            p.getQtd(),
	    p.getTamanho(),
            p.getCor(),
	    p.getValorcp(),
	    p.getValorvd()
        });
        }
        
    } 
    
        
            
    public void readProdutoViewForBusca(String bus){
        DefaultTableModel modelo = (DefaultTableModel) tblProduto.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();
        
        for(Produto p: pdao.readBusca(bus)) {
            modelo.addRow(new Object[]{
            p.getCod(),
            p.getNomeprod(),
            p.getFornecedorp(),
            p.getQtd(),
	    p.getTamanho(),
            p.getCor(),
	    p.getValorcp(),
	    p.getValorvd()
        });
        }
        
    } 
    
     Vector<Integer> objf = new Vector<Integer>();
    
    public void restaurarCombobox() {
        try { 
           ProdutoDAO objfornecedordao = new ProdutoDAO();
           ResultSet rs = objfornecedordao.listaFornecedor();
            while(rs.next()){
               objf.addElement(rs.getInt(1));
               boxNomeFor.addItem(rs.getNString(2));
            }
           
           }           
       catch (SQLException erro) {
           JOptionPane.showMessageDialog(null, "Erro ao listar "+erro);
       }
    }
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomePro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtTamanho = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBuscaprod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        spiQuantidade = new javax.swing.JSpinner();
        boxNomeFor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        txtValorCompra = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        btnAltualizar = new javax.swing.JButton();
        btnBuscaprod = new javax.swing.JButton();
        txtValorVenda = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCod = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Financeiro Chloe");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon.png")).getImage());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PRODUTOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        txtNomePro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Fornecedor:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Quantidade:");

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtTamanho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tamanho:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Valor de Compra:");

        txtBuscaprod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Valor de Venda:");

        txtCor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Cor:");

        spiQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        boxNomeFor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        boxNomeFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNomeForActionPerformed(evt);
            }
        });

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Fornecedor", "Quantidade", "Tamanho", "Cor", "Valor de Compra", "Valor de Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduto.getTableHeader().setReorderingAllowed(false);
        tblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutoMouseClicked(evt);
            }
        });
        tblProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblProdutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        txtValorCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAltualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAltualizar.setText("Atualizar");
        btnAltualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltualizarActionPerformed(evt);
            }
        });

        btnBuscaprod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscaprod.setText("Pesquisar");
        btnBuscaprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaprodActionPerformed(evt);
            }
        });

        txtValorVenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Codigo:");

        txtCod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCod.setText("0");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Nome Produto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomePro, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxNomeFor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spiQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(26, 26, 26)
                        .addComponent(btnExcluir)
                        .addGap(29, 29, 29)
                        .addComponent(btnAltualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscaprod, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscaprod))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNomePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(boxNomeFor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtCod))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaprod)
                    .addComponent(btnAdd)
                    .addComponent(btnExcluir)
                    .addComponent(btnAltualizar)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProActionPerformed

    private void boxNomeForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNomeForActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_boxNomeForActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        int codf;
        codf = objf.get(boxNomeFor.getSelectedIndex()-1);

        Produto p = new Produto();
        ProdutoDAO pdao = new ProdutoDAO();
        p.setNomeprod(txtNomePro.getText());
        p.setCodfor(codf);
        p.setQtd(Integer.parseInt(spiQuantidade.getValue().toString()));
        p.setTamanho(txtTamanho.getText());
        p.setCor(txtCor.getText());
        p.setValorcp(Double.parseDouble(txtValorCompra.getText()));
        p.setValorvd(Double.parseDouble(txtValorVenda.getText()));
        pdao.create(p);
       
        txtNomePro.setText("");
        txtTamanho.setText("");
        txtCor.setText("");
        txtValorCompra.setText("");
        txtValorVenda.setText("");
        
        readProdutoView();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblProduto.getSelectedRow();
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(this, "Favor selecionar uma linha valida!");
        }else{
            DefaultTableModel tabelaProduto = (DefaultTableModel) tblProduto.getModel();
            int i = JOptionPane.showConfirmDialog(this, "Deseja excluir essa linha?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if(i == 0){
                    Produto p = new Produto();
                    ProdutoDAO pdao = new ProdutoDAO();
                    p.setCod((int)tblProduto.getValueAt(tblProduto.getSelectedRow(), 0));
                    pdao.delete(p);
                    
                    txtNomePro.setText("");
                    txtTamanho.setText("");
                    txtCor.setText("");
                    txtValorCompra.setText("");
                    txtValorVenda.setText("");                   
                    readProdutoView();
                    
            JOptionPane.showMessageDialog(this, "Excluido com sucesso!");
            }
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAltualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltualizarActionPerformed
        // TODO add your handling code here:
                  
            
            if(tblProduto.getSelectedRow() != -1){ 
                int codf;
                codf = objf.get(boxNomeFor.getSelectedIndex()-1);
                Produto p = new Produto();
                ProdutoDAO pdao = new ProdutoDAO();
                 p.setCodfor(codf);
                 p.setNomeprod(txtNomePro.getText());
                 p.setQtd(Integer.parseInt(spiQuantidade.getValue().toString()));
                 p.setTamanho(txtTamanho.getText());
                 p.setCor(txtCor.getText());
                 p.setValorcp(Double.parseDouble(txtValorCompra.getText()));
                 p.setValorvd(Double.parseDouble(txtValorVenda.getText()));
                 p.setCod((int)tblProduto.getValueAt(tblProduto.getSelectedRow(), 0));
                 pdao.update(p);
        }     
            txtNomePro.setText("");
            txtTamanho.setText("");
            txtCor.setText("");
            txtValorCompra.setText("");
            txtValorVenda.setText("");                   
            readProdutoView();
        
        
    }//GEN-LAST:event_btnAltualizarActionPerformed

    private void btnBuscaprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaprodActionPerformed
        // TODO add your handling code here:
        readProdutoViewForBusca(txtBuscaprod.getText());
        
    }//GEN-LAST:event_btnBuscaprodActionPerformed

    private void tblProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutoMouseClicked
        // TODO add your handling code here:
        if(tblProduto.getSelectedRow() != -1){
            txtCod.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 0).toString());
            txtNomePro.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 1).toString());
            boxNomeFor.setSelectedItem(tblProduto.getValueAt(tblProduto.getSelectedRow(), 2));
            spiQuantidade.setValue(tblProduto.getValueAt(tblProduto.getSelectedRow(), 3));
            txtTamanho.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 4).toString());
            txtCor.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 5).toString());
            txtValorCompra.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 6).toString());
            txtValorVenda.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 7).toString());
          
        }
        
    }//GEN-LAST:event_tblProdutoMouseClicked

    private void tblProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProdutoKeyReleased
        // TODO add your handling code here:
        if(tblProduto.getSelectedRow() != -1){
            txtCod.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 0).toString());
            txtNomePro.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 1).toString());
            boxNomeFor.setSelectedItem(tblProduto.getModel().getValueAt(tblProduto.getSelectedRow(), 2).toString());
            spiQuantidade.setValue(tblProduto.getValueAt(tblProduto.getSelectedRow(), 3));
            txtTamanho.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 4).toString());
            txtCor.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 5).toString());
            txtValorCompra.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 6).toString());
            txtValorVenda.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 7).toString());
            
        }
    }//GEN-LAST:event_tblProdutoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> boxNomeFor;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAltualizar;
    private javax.swing.JButton btnBuscaprod;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spiQuantidade;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtBuscaprod;
    private javax.swing.JLabel txtCod;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtNomePro;
    private javax.swing.JTextField txtTamanho;
    private javax.swing.JTextField txtValorCompra;
    private javax.swing.JTextField txtValorVenda;
    // End of variables declaration//GEN-END:variables
}
